apiVersion: v1  # API version to use
kind: Service  # Kind of Kubernetes object to create
metadata:
  name: mongo-service  # Name of the Service
spec:
  ports:
  - port: 27017  # The port that the Service will listen on
    targetPort: 27017  # The port on the target pods where this Service is directed
  selector:
    app: mongo  # Label to identify the pods that this Service will route traffic to