apiVersion: v1  # API version to use
kind: Secret  # Kind of Kubernetes object to create
metadata:
  name: mongo-credentials  # Name of the Secret
type: Opaque  # Type of the Secret, Opaque is the default and is used for arbitrary user-defined data
data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # MongoDB root username, base64 encoded (decoded value is "admin")
  MONGO_ROOT_PASSWORD:  c3VwZXJzZWNyZXRwYXNzd29yZA==  # MongoDB root password, base64 encoded (decoded value is "supersecretpassword")