apiVersion: v1  # API version to use
kind: PersistentVolume  # Kind of Kubernetes object to create
metadata:
  name: mongo-pv  # Name of the PersistentVolume
spec:
  capacity:
    storage: 1000Mi  # Amount of storage allocated to the PersistentVolume
  accessModes:
    - ReadWriteOnce  # Access mode, ReadWriteOnce means the volume can be mounted as read-write by a single node
  storageClassName: hostpath  # Name of the StorageClass
  volumeMode: Filesystem  # The volume's mode. Filesystem means it's accessible as a filesystem
  persistentVolumeReclaimPolicy: Retain  # Policy for when the PersistentVolume is released. Retain means it's not automatically deleted
  hostPath:
    path: "/tmp"  # Path on the host where the data is stored
---
apiVersion: v1  # API version to use
kind: PersistentVolumeClaim  # Kind of Kubernetes object to create
metadata:
  name: mongo-pvc  # Name of the PersistentVolumeClaim
spec:
  resources:
    requests:
      storage: 500Mi  # Amount of storage requested by the PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce  # Access mode, ReadWriteOnce means the volume can be mounted as read-write by a single node